kubectl delete pods --all -n calico-apiserver
kubectl delete pods --all -n calico-system
kubectl delete pods --all -n cert-manager
kubectl delete pods --all -n default
kubectl delete pods --all -n flink
kubectl delete pods --all -n fluent
kubectl delete pods --all -n eco-system
kubectl delete pods --all -n ingress-apisix
kubectl delete pods --all -n istio-operator
kubectl delete pods --all -n k8ssandra-operator
kubectl delete pods --all -n kafka
kubectl delete pods --all -n strimzi-drain-cleaner
kubectl delete pods --all -n keycloak-operator
kubectl delete pods --all -n kube-node-lease
kubectl delete pods --all -n kube-public
kubectl delete pods --all -n postgres
kubectl delete pods --all -n redis
kubectl delete pods --all -n kubernetes-dashboard
kubectl delete pods --all -n local-path-storage
kubectl delete pods --all -n metallb-system
kubectl delete pods --all -n monitoring
kubectl delete pods --all -n observability
kubectl delete pods --all -n opensearch-operator-system
kubectl delete pods --all -n opentelemetry-operator-system
kubectl delete pods --all -n tigera-operator
kubectl delete pods --all -n istio-system
# kubectl delete pods --all -n vault
# kubectl delete pods --all -n wireguard
kubectl delete pods --all -n rook-ceph
kubectl delete pods --all -n kube-system