{
 "title": "Redpanda",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(instance)" },
   { "name": "node_shard", "label": "Shard", "query": "label_values(shard)" },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "Cluster : cluster,Instance : instance,Instance\\,Shard : instance\\,shard"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Redpanda Summary</h1>"
  },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (app) (vectorized_application_uptime)",
     "legendFormat": "Nodes Up"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (topic,partition) (vectorized_storage_log_partition_size{namespace=\"kafka\"}))",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "kafka_rpc: Latency  (p95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vectorized_kafka_rpc_dispatch_handler_latency_bucket{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by (le, $aggr_criteria))",
     "legendFormat": "node: {{instance}}, shard: {{shard}}"
    }
   ]
  },
  {
   "title": "kafka_rpc: Latency  (p99)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_kafka_rpc_dispatch_handler_latency_bucket{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by (le, $aggr_criteria))",
     "legendFormat": "node: {{instance}}, shard: {{shard}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Internal RPC Latency</h1>"
  },
  {
   "title": "internal_rpc: Latency  (p95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vectorized_internal_rpc_dispatch_handler_latency_bucket{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by (le, $aggr_criteria))",
     "legendFormat": "node: {{instance}}, shard: {{shard}}"
    }
   ]
  },
  {
   "title": "internal_rpc: Latency  (p99)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vectorized_internal_rpc_dispatch_handler_latency_bucket{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by (le, $aggr_criteria))",
     "legendFormat": "node: {{instance}}, shard: {{shard}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 20 },
   "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Throughput</h1>"
  },
  {
   "title": "Rate - Total number of bytes read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vectorized_storage_log_read_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
     "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Rate - Total number of bytes written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vectorized_storage_log_written_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
     "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - The total number of errors while reading http requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_httpd_read_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, service: {{service}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - The total number of errors while replying to http",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_httpd_reply_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, service: {{service}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of errors when shutting down the connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_connection_close_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of requests with not available RPC method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_method_not_found_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of service errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_service_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of errors when shutting down the connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_connection_close_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of requests with not available RPC method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_method_not_found_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of service errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_service_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of failed heartbeat requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_heartbeat_requests_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of failed recovery requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_recovery_requests_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of failed replicate requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_replicate_request_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total aio errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_aio_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of errors in client correlation id",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_client_correlation_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number of connection errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_connection_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number of errors while dispatching responses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_read_dispatch_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number or requests errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_request_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number of responses with wrong correlation id",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_server_correlation_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number of batch parsing (reading) errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_batch_parse_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of batch write errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_batch_write_errors{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "io_queue",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Consumed disk capacity units adjusted for class shares and idling preemption",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_adjusted_consumption{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}, stream: {{stream}}"
      }
     ]
    },
    {
     "title": "Rate - Accumulated disk capacity units consumed by this class; an increment per-second rate indicates full utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_consumption{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}, stream: {{stream}}"
      }
     ]
    },
    {
     "title": "random delay time in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_io_queue_delay{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of requests in the disk",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_io_queue_disk_queue_length{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of requests in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_io_queue_queue_length{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "current amount of shares",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_io_queue_shares{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total time spent starving for disk",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_starvation_time_sec{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total bytes passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total time spent in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_delay_sec{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total time spent in disk",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_exec_sec{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total operations passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_operations{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total read bytes passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_read_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total read operations passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_read_ops{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes split",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_split_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of requests split",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_split_ops{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total write bytes passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_write_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total write operations passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_io_queue_total_write_ops{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "kafka_rpc",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "kafka_rpc: Currently active connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_kafka_rpc_active_connections{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of connections rejected for hitting connection limits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_connections_rejected{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of connections are blocked by connection rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_connections_wait_rate{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of accepted connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_connects{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Memory consumed by request processing",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_consumed_mem_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of requests with corrupted headers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_corrupted_headers{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "kafka_rpc: Latency ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_kafka_rpc_dispatch_handler_latency{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Maximum memory allowed for RPC",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_max_service_mem_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of bytes received from the clients in valid requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_received_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of requests blocked in memory backpressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_requests_blocked_memory{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of successful requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_requests_completed{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "kafka_rpc: Number of requests being processed by server",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_kafka_rpc_requests_pending{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - kafka_rpc: Number of bytes sent to clients",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_kafka_rpc_sent_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_memory_allocated_memory{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of cross cpu free",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_memory_cross_cpu_free_operations{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Free memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_memory_free_memory{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of free operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_memory_free_operations{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total count of failed memory allocations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_memory_malloc_failed{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of live objects",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_memory_malloc_live_objects{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of malloc operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_memory_malloc_operations{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total reclaims operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_memory_reclaims_operations{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Total memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_memory_total_memory{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "others",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current receive batch queue length",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_alien_receive_batch_queue_length{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of received messages",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_alien_total_received_messages{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of sent messages",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_alien_total_sent_messages{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Redpanda build information",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_application_build{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, revision: {{revision}}, shard: {{shard}}, version: {{version}}"
      }
     ]
    },
    {
     "title": "Redpanda uptime in milliseconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_application_uptime{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of partitions with ongoing/requested operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_controller_pending_partition_operations{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of queued node operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_members_backend_queued_node_operations{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes fetched",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_cluster_partition_bytes_fetched_total{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes produced",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_cluster_partition_bytes_produced_total{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Partition commited offset. i.e. safely persisted on majority of replicas",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_committed_offset{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Last offset stored by current partition on this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_end_offset{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Partion high watermark i.e. highest consumable offset",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_high_watermark{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Last stable offset",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_last_stable_offset{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Flag indicating if this partition instance is a leader",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_leader{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Id of current partition leader",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_leader_id{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Amount of partitions that are moving from node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_moving_from_node{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Amount of partitions that are moving to node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_moving_to_node{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Amount of cancelling partition movements for node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_node_cancelling_movements{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of records fetched",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_cluster_partition_records_fetched{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of records produced",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_cluster_partition_records_produced{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Number of under replicated replicas",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_cluster_partition_under_replicated_replicas{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "The current number of open  connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_httpd_connections_current{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, service: {{service}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - The total number of connections opened",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_httpd_connections_total{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, service: {{service}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - The total number of http requests served",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_httpd_requests_served{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, service: {{service}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Fetch sessions cache memory usage in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_kafka_fetch_sessions_cache_mem_usage_bytes{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Total number of fetch sessions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_kafka_fetch_sessions_cache_sessions_count{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Fetch Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_kafka_latency_fetch_latency_us{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, latency_metric: {{latency_metric}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Produce Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_kafka_latency_produce_latency_us{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, latency_metric: {{latency_metric}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of errors attempting to transfer leader",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_leader_balancer_leader_transfer_error{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of times no balance improvement was found",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_leader_balancer_leader_transfer_no_improvement{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of successful leader transfers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_leader_balancer_leader_transfer_succeeded{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of timeouts attempting to transfer leader",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_leader_balancer_leader_transfer_timeout{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of node status RPCs received by this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_node_status_rpcs_received{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of node status RPCs sent by this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_node_status_rpcs_sent{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of timed out node status RPCs from this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_node_status_rpcs_timed_out{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Request latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_pandaproxy_request_latency{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, operation: {{operation}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of reported stalls, look in the traces for the exact reason",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_stall_detector_reported{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "raft",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indicates if current raft group configuration is in joint state i.e. configuration is being changed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_raft_configuration_change_in_progress{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of finished replicate requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_done_replicate_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Number of raft groups",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_raft_group_count{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of groups for which node is a leader",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_raft_leader_for{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of leadership changes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_leadership_changes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of log flushes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_log_flushes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of log truncations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_log_truncations{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of append requests received",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_received_append_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of vote requests received",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_received_vote_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Bandwidth available for partition movement. bytes/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_raft_recovery_partition_movement_available_bandwidth{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of replicate requests with quorum ack consistency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_replicate_ack_all_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of replicate requests with leader ack consistency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_replicate_ack_leader_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of replicate requests with no ack consistency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_replicate_ack_none_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of vote requests sent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_raft_sent_vote_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "reactor",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Total number of abandoned failed futures, futures destroyed while still containing an exception",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_abandoned_failed_futures{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total aio-reads bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_aio_bytes_read{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total aio-writes bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_aio_bytes_write{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of aio operations that exceed IO limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_aio_outsizes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total aio-reads operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_aio_reads{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total aio-writes operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_aio_writes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of C++ exceptions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_cpp_exceptions{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total cpu busy time in milliseconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_cpu_busy_ms{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total steal time, the time in which some other process was running while Seastar was not trying to run (not sleeping).Because this is in userspace, some time that could be legitimally thought as steal time is not accounted as such. For example, if we are sleeping and can wake up but the kernel hasn't woken us up yet.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_cpu_steal_time_ms{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Counts bytes read from disk file streams.  A high rate indicates high disk activity. Divide by fstream_reads to determine average read size.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_fstream_read_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Counts the number of bytes read from disk that could not be satisfied from read-ahead buffers, and had to block. Indicates short streams, or incorrect read ahead configuration.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_fstream_read_bytes_blocked{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Counts reads from disk file streams.  A high rate indicates high disk activity. Contrast with other fstream_read* counters to locate bottlenecks.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_fstream_reads{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Counts the number of buffered bytes that were read ahead of time and were discarded because they were not needed, wasting disk bandwidth. Indicates over-eager read ahead configuration.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_fstream_reads_ahead_bytes_discarded{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Counts the number of times a buffer that was read ahead of time and was discarded because it was not needed, wasting disk bandwidth. Indicates over-eager read ahead configuration.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_fstream_reads_aheads_discarded{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Counts the number of times a disk read could not be satisfied from read-ahead buffers, and had to block. Indicates short streams, or incorrect read ahead configuration.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_fstream_reads_blocked{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of fsync operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_fsyncs{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of io-threaded-fallbacks operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_io_threaded_fallbacks{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of logging failures",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_logging_failures{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of times pollers were executed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_polls{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of pending tasks in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_reactor_tasks_pending{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total tasks processed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_reactor_tasks_processed{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of tasks in the timer-pending queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_reactor_timers_pending{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_reactor_utilization{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "rpc_client",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently active connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_rpc_client_active_connections{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Connection attempts",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_connects{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number of responses with corrupted headers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_corrupted_headers{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes sent (including headers)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_in_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes received",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_out_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number or requests timeouts",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_request_timeouts{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number of requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_requests{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Rate - Number of requests that are blocked because of insufficient memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_rpc_client_requests_blocked_memory{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    },
    {
     "title": "Number of requests pending",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_rpc_client_requests_pending{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}, target: {{target}}, connection_cache_label: {{connection_cache_label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "scheduler",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of backlog on this queue, in tasks; indicates whether the queue is busy and/or contended",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_scheduler_queue_length{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, group: {{group}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Accumulated runtime of this task queue; an increment rate of 1000ms per second indicates full utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_scheduler_runtime_ms{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, group: {{group}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Shares allocated to this queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_scheduler_shares{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, group: {{group}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Accumulated starvation time of this task queue; an increment rate of 1000ms per second indicates the scheduler feels really bad",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_scheduler_starvetime_ms{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, group: {{group}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Count of tasks executing on this queue; indicates together with runtime_ms indicates length of tasks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_scheduler_tasks_processed{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, group: {{group}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total amount in milliseconds we were in violation of the task quota",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_scheduler_time_spent_on_task_quota_violations_ms{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, group: {{group}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Accumulated waittime of this task queue; an increment rate of 1000ms per second indicates queue is waiting for something (e.g. IO)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_scheduler_waittime_ms{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, group: {{group}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "storage",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "controller backlog",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_storage_compaction_backlog_controller_backlog_size{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "current controller error, i.e difference between set point and backlog size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_storage_compaction_backlog_controller_error{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "controller output, i.e. number of shares",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_storage_compaction_backlog_controller_shares{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Size of the database in memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_storage_kvstore_cached_bytes{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of entries fetched",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_kvstore_entries_fetched{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of entries removaled",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_kvstore_entries_removed{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of entries written",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_kvstore_entries_written{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of keys in the database",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_kvstore_key_count{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Number of segments rolled",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_kvstore_segments_rolled{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of batches read",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_batches_read{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of batches written",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_batches_written{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Reader cache hits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_cache_hits{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Reader cache misses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_cache_misses{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of cached batches read",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_cached_batches_read{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of cached bytes read",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_cached_read_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of compacted segments",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_compacted_segment{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Average segment compaction ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_compaction_ratio{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of times we had to re-construct the .compaction index on a segment",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_corrupted_compaction_indices{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of active log segments",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_log_segments_active{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of created log segments",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_log_segments_created{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of removed log segments",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_log_segments_removed{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Current size of partition in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_storage_log_partition_size{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes read",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_read_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of readers added to cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_readers_added{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Number of readers evicted from cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_readers_evicted{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes written",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_written_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Batch cache hit ratio - batches",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_cached_batches_read{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria) / sum(irate(vectorized_storage_log_batches_read{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Batch cache hit ratio - bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_storage_log_cached_read_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria) / sum(irate(vectorized_storage_log_read_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, namespace: {{namespace}}, partition: {{partition}}, shard: {{shard}}, topic: {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vectorized_internal_rpc",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "internal_rpc: Currently active connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_internal_rpc_active_connections{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of connections rejected for hitting connection limits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_connections_rejected{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of connections are blocked by connection rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_connections_wait_rate{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of accepted connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_connects{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Memory consumed by request processing",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_consumed_mem_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of requests with corrupted headers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_corrupted_headers{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "internal_rpc: Latency ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_internal_rpc_dispatch_handler_latency{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Internal RPC service latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_internal_rpc_latency{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, method: {{method}}, service: {{service}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Maximum memory allowed for RPC",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_max_service_mem_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of bytes received from the clients in valid requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_received_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of requests blocked in memory backpressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_requests_blocked_memory{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of successful requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_requests_completed{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "internal_rpc: Number of requests being processed by server",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vectorized_internal_rpc_requests_pending{instance=~\"$node\",shard=~\"$node_shard\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - internal_rpc: Number of bytes sent to clients",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vectorized_internal_rpc_sent_bytes{instance=~\"$node\",shard=~\"$node_shard\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  }
 ]
}