FROM docker:23.0.1-dind

RUN addgroup -S --gid 9999 flink

# docker pull docker:23.0.1-dind
# docker build . --no-cache --progress=plain --tag=k8s-lb:5000/docker:23.0.1.1-dind
# docker push k8s-lb:5000/docker:23.0.1.1-dind
# sudo crictl rmi --prune